CREATE TABLE `m_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `app_client_id` varchar(255) DEFAULT NULL,
  `app_token` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `created_dt` datetime DEFAULT NULL,
  `email_id` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `group_id` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `modified_dt` datetime DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `token_validity_dt` datetime DEFAULT NULL,
  `user_access_dt` datetime DEFAULT NULL,
  `user_name` varchar(255) DEFAULT NULL,
  `user_type` varchar(255) DEFAULT NULL,
  `emp_code` varchar(25) DEFAULT NULL,
  `emp_designation` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_name_UNIQUE` (`app_client_id`,`user_name`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

CREATE TABLE `t_payroll_dtl` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t_payroll_hdr_id` int(11) DEFAULT NULL,
  `entry_type` varchar(25) DEFAULT NULL,
  `entry_code` varchar(25) DEFAULT NULL,
  `entry_name` varchar(25) DEFAULT NULL,
  `ytd` decimal(10,0) DEFAULT NULL,
  `entry_amount` decimal(10,0) DEFAULT NULL,
  `status_code` varchar(25) DEFAULT NULL,
  `is_enabled` char(1) DEFAULT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_dt` datetime DEFAULT NULL,
  `modified_by` varchar(50) DEFAULT NULL,
  `modified_dt` datetime DEFAULT NULL,
  `remarks` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `t_payroll_hdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t_payroll_batch_id` int(11) DEFAULT NULL,
  `t_emp_pay_adj_id` int(11) DEFAULT NULL,
  `m_emp_id` int(11) DEFAULT NULL,
  `m_emp_pay_structure_id` int(11) DEFAULT NULL,
  `month` int(11) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `emp_code` varchar(25) DEFAULT NULL,
  `emp_fname` varchar(200) DEFAULT NULL,
  `emp_lname` varchar(200) DEFAULT NULL,
  `pf_no` varchar(50) DEFAULT NULL,
  `emp_grade` varchar(50) DEFAULT NULL,
  `bank_account_no` varchar(25) DEFAULT NULL,
  `designation` varchar(100) DEFAULT NULL,
  `dob` datetime DEFAULT NULL,
  `payment_mode` varchar(25) DEFAULT NULL,
  `bank_ifsc_code` varchar(25) DEFAULT NULL,
  `bank_name` varchar(200) DEFAULT NULL,
  `bank_branch_name` varchar(100) DEFAULT NULL,
  `total_ctc` decimal(10,0) DEFAULT NULL,
  `total_earnings` decimal(10,0) DEFAULT NULL,
  `total_deductions` decimal(10,0) DEFAULT NULL,
  `net_salary` decimal(10,0) DEFAULT NULL,
  `is_enabled` char(1) DEFAULT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_dt` datetime DEFAULT NULL,
  `modified_by` varchar(50) DEFAULT NULL,
  `modified_dt` datetime DEFAULT NULL,
  `remarks` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
