// Generated by https://quicktype.io

export class FAQ {
    id:           number;
    mFaqCatId:    string;
    header:       string;
    faqCatName:string;
    faqCatDesc:string;
    totalLike:    string;
    totalDisLike: string;
    post:         string;
    faqLikes:     FAQLike[];
    faqComments:  any[];
    faqRefLinks:  any[];
    faqTags:      FAQTag[];
    isEnabled:    string;
    createdBy:    string;
    createdDt:    string;
    modifiedBy:   string;
    modifiedDt:   string;
}

export class FAQLike {
    id:         number;
    isLiked?:   string;
    isEnabled:  string;
    createdBy:  string;
    createdDt:  string;
    modifiedBy: string;
    modifiedDt: string;
    tfaqId:     string;
    tagName?:   string;
    mtagId?:    string;
}

export class FAQTag {
    id:         number;
    tagName:    string;
    isEnabled:  string;
    createdBy:  string;
    createdDt:  string;
    modifiedBy: string;
    modifiedDt: string;
    mtagId:     number;
    dummyTagId: number;
    tfaqId:     string;
}
export class FAQComment {
    id:         number;
    comment:    string;
    isEnabled:  string;
    createdBy:  string;
    createdDt:  string;
    modifiedBy: string;
    modifiedDt: string;    
    tfaqId:     string;
}

export class FAQRefLink {
    id:         number;
    refLink:    string;
    refLinkTitle:string;
    isEnabled:  string;
    createdBy:  string;
    createdDt:  string;
    modifiedBy: string;
    modifiedDt: string;    
    tfaqId:     string;
}

