// Generated by https://quicktype.io

export class CashBalance {
    id:              number;
    employeeId:      string;
    empName:         string="";
    importDt:        string;
    payToCompAmt:    string;
    payToEmpAmt:     string;
    cashBalImportId: null;
    isEnabled:       string;
    createdBy:       string;
    modifiedBy:      null;
    createdDt:       null;
    modifiedDt:      null;
}
