


// Generated by https://quicktype.io

export class Expense {
    id:                     number;
    expenseClaimCode:       string;
    isBillable:             string;
    isJobBased:             string;
    jobId:                  string;
    jobCode:                string;
    jobName:                string;
    partnerId:              string;
    partnerName:            string;
    costCenterId:           string;
    costCenterCode:         string;
    expPdfId:               string;
    costCenterName:         string;
    expenseClaimStatus:     string;
    expenseClaimStatusName: string;
    employeeId:             string;
    employeeCode:           string;
    employeeFName:          string;
    employeeLName:          string;
    expenseClaimAmount:     number;
    totalEntitledAmount:    number;
    empRemarks:             string;
    appliedEmpId:           string;
    appliedEmpCode:         string;
    appliedEmpFName:        string;
    appliedEmpLName:        string;
    appliedDt:              string;
    dummyAppliedDt:         string;
    validateUserGroupId:    string;
    validateUserGroupName:  string;
    validateDecision:       string;
    validateRemarks:        string;    
    validatedDt:            string;
    validateEmpId:          string;
    validateEmpFName:       string;
    validateEmpLName:       string;
    n1Decision:             string;
    n1ApprovedDt:           string;
    n1Remarks:              string;
    n1EmpId:                string;
    n1EmpCode:              string;
    n1EmpFName:             string;
    n1EmpLName:             string;
    n1DecisionDt:           string;
    needN2Approval:         string;
    n2Decision:             string;
    n2ApprovedDt:           string;
    n2EmpId:                string;
    n2EmpCode:              string;
    n2EmpFName:             string;
    n2EmpLName:             string;
    n2Remarks:              string;
    settleUserGroupId:      string;
    settleUserGroupName:    string;
    settleDecision:         string;
    inputCreditAmount:      string;
    settleEmpId:            string;
    settleEmpName:          string;
    settleRemarks:          string;
    settledDt:              string;
    cancelledDt:            string;
    cancelRemarks:          string;
    cancelEmpId:            string;
    cancelEmpFName:         string;
    cancelEmpLName:         string;
    isEnabled:              string;
    createdBy:              string;
    modifiedBy:             string;
    createdDt:              string;
    modifiedDt:             string;
    expenseClaimBills:      ExpenseClaimBill[];
}

export class ExpenseClaimBill {
    id:                  number;
    expenseClaimId:      string;
    billDt:              string;
    categoryId:          string;
    categoryName:        string='';
    subCategoryId:       string;
    subCategoryName:     string='';
    merchantId:          string;
    merchantName:        string;
    isBillable:          string;
    isExpBillable:       string;
    billedOnCompanyName: string;
    billAmount:          number;
    billNo:              string;
    billStatus:          string;
    entitledAmount:      number;
    billRemarks:         string;
    docId:               string;
    isEnabled:           string;
    createdBy:           string;
    modifiedBy:          string;
    createdDt:           string;
    modifiedDt:          string;
}
