export class Interview {
    id:                      number;
    incidentId:              string;
    incidentName:            string;
    applicantId:             string;
    vcId:                    string;
    vcCode:                  string;
    vcSummary:               string;
    applicantName:           string;
    interviewDate:           string;
    interviewRound:          InterviewRound[];
    applicant:          IncidentApplicant[];
    resumeDocId:             string;
    coverLetter:             string;
    finalDecision:           string;
    finalDecisionRemarks:    string;
    finalDecisionEmpId:      string;
    firstInterviewerId:      string;
    firstInterviewerStatus:  string;
    secondInterviewerId:     string;
    secondInterviewerStatus: string;
    thirdInterviewerId:      string;
    thirdInterviewerStatus:  string;
    isEnabled:               string;
    createdBy:               string;
    modifiedBy:              string;
    createdDt:               string;
    modifiedDt:              string;
}

export class InterviewRound {
    id:               number;
    interviewId:      string;
    roundName:        string;
    roundDateTime:    string;
    roundCompletedDt: string;
    roundOrder:       string;
    interviewEmpId:   string;
    interviewEmpName: string;
    decision:         string;
    finalDecision:    string;
    rating:           string;
    remarks:          string;
    isEnabled:        string;
    createdBy:        string;
    createdDt:        string;
    modifiedBy:       string;
    modifiedDt:       string;
    dummyDate:        string;
}

export class IncidentApplicant {
    id:                   number;
    incidentId:           string;
    vcId:                 string;
    source:               string;
    editApplicantId:      string ;
    arrayIndex:           string;
    referredByEmpId:      string;
    referredByEmpName:    string;
    firstName:            string;
    lastName:             string;
    mobileNumber:         string;
    email:                string;
    dob:                  Date;
    currCompany:          string;
    currDesignation:      string;
    currExperience:       string;
    currLocation:         string;
    currSalary:           string;
    testEligibilityStatus:string;
    currentStatusForTest: string;
    institute:            string;
    course:               string;
    passoutYear:          string;
    marks:                string;
    historyOfArrears:     string;
    resumeDocId:          string;
    coverLetter:          string;
    applicationDt:        string;
    isShortListed:        string;
    isApplicantScheduled: string;
    isEligibleForTest:    string;
    isTestScheduled:      string;
    isInterviewScheduled: string;
    isInterviewEligible:  string;
    testScheduledDt:      Date;
    shortListedDt:        string;
    slByEmpId:            string;
    firstInterviewerId:   string;
    secondInterviewerId:  string;
    thirdInterviewerId:   string;
    scheduledInterviewDt: string;
    interviewScheduledDt: Date;
    interviewId:          string;
    applicantId:          string;
    expType:              string;
    isEnabled:            string;
    createdBy:            string;
    createdDt:            string;
    modifiedBy:           string;
    modifiedDt:           string;
    finalTestStatus:      string;
    finalInterviewStatus: string;
    finalDecision:        string;
    reject:               string;
    onhold:               string;
    approve:              string;
    testScheduledStatus:  string;    
    isAttended:           string;
    certificateIssued:    string;
    score:                string;
    reallocateMessage:    string;
    remarksFromTrainer:   string;
    skillsAcquired:       string;
    certificateIssuedDate:string;
    docId:                string;
    isReallocate:         string;
    select:               boolean;
    isDocUpload:boolean=false;
    isExperiencedType:any;
    isEditApplicant:boolean=false;
    isApplicantDetails:boolean;
    isviewApplicantDetails:boolean;
    degreeName:String;
    employeeCode:         string;
    errorCode:string;
    errorDesc:string;
    errorMessage:string;
    userName:string;
    password:string;
}
