export const status_css={
    'official-information-pending':'info',
    'INPROGRESS':'info',
    'voluntary':'info',
    'PENDING-EMP-ACCEPTANCE':'info',
    'ACTIVE': 'success',
    'PENDING':'info',
    'APPROVED': 'success',
    'SETTLED': 'success',
    'COMPLETED': 'success',
    'OPEN' : 'success',
    ' OPEN ' : 'info',
    'FREEZE' : 'info',
    'PROCESSING-SALARY RECORDS' : 'info',
    'EASY':'success',
    'SELECTED' : 'success',
    'PENDING-SELF-APPRAISAL':'warning',
    'EMP-ACCEPTANCE':'warning',
    'MEDIUM':'warning',
    'CREATED' : 'warning',
    'APPLIED' : 'warning',    
    'ONBOARD-APPROVAL-PENDING' : 'warning',
    'DIR-APPROVAL-PENDING' : 'warning',
    'PROFILE-CONFIRMATION-PENDING' : 'warning',
    'PROFILE-COMPLETED' : 'warning',
    'PROFILE-VALIDATION-PENDING' : 'warning',
    'PROFILE-VALIDATED' : 'warning',
    'SKILL-VALIDATION-PENDING' : 'warning',
    'SKILL-VALIDATED' : 'warning',
    'PENDING-APPROVAL' : 'warning',
    'PROCESSING' : 'warning',
    'ONBOARDED' : 'warning',
    'ON HOLD':'warning',
    'ON-HOLD':'warning',
    'PARTIALLY APPROVED' : 'warning',
    'ACC2-APPROVAL-PENDING':'warning',
    'N1-APPROVAL-PENDING':'warning',
    'PENDING-N1-REVIEW':'warning',
    'PENDING-N2-REVIEW':'warning',
    'Y':'danger',
    'N':'warning',
    'SETTLEMENT-PENDING':'warning',
    'VALIDATION-PENDING':'warning', 
    'N2-APPROVAL-PENDING':'warning',
    'PENDING-ACCOUNT-CLEARENCE':'warning',
    'PENDING-HR-CLEARENCE':'warning',
    'PENDING-N1-CLEARENCE':'warning',
    'VALIDATION-REJECTED': 'danger', 
    'SETTLED-REJECTED': 'danger',
    'ACC2-REJECTED': 'danger',
    'REJECTED': 'danger',
    'VOID': 'danger',
    'N1-REJECTED':'danger',
    'N2-REJECTED':'danger',
    'CANCELLED':'danger',
    'involuntary':'danger',
    'TOUGH':'danger',
    'fail':'danger',
    'FAIL':'danger',
    'PASS':'success',
    'pass':'success',
    'error':'danger',
    'ERROR':'danger',
    'CLOSED':'danger',
    'Employee-conversion-in-progress' :'warning',
    'Employee-conversion-intitated':'warning',
    'Created':'success',
    'Error':'danger',
    'employee-conversion-Completed':'success',
    'No-Applicant-in-master':'warning',
    'Completed':'success',
    'Success':'success',
    'in-progress':'primary',
    'Rejected':'danger',
    'Approved':'success',
    'on-hold':'warning',
    'in-hold':'warning'

}

	