export class ExpenseClaim{
    id:string;
    expenseClaimCode:string;
    isBillable:string;
    jobId:string;
    jobCode:string;
    jobName:string;
    partnerId:string;
    partnerName:string;
    costCenterId:string;
    costCenterCode:string;
    costCenterName:string;
    expenseClaimStatus:string;
    expenseClaimStatusName:string;
    employeeId:string;
    employeeCode:string;
    employeeName:string;
    expenseClaimAmount:string;
    empRemarks:string;
    isApplied:string;
    appliedEmpId:string;
    appliedEmpName:string;
    appliedDt :string = new Date().toJSON();
    isValid:string;
    validateEmpId:string;
    validateEmpName:string;
    validateRemarks:string;
    validationDt:string = new Date().toJSON();
    isApproved:string;
    approvedDt:string  = new Date().toJSON();
    managerEmpId:string;
    managerEmpName:string;
    managerRemarks:string;
    needManager2Approval:string;
    isManager2Approved:string;
    manager2ApprovedDt:string = new Date().toJSON();
    manager2EmpId:string;
    manager2EmpName:string;
    manager2Remarks:string;
    isAccountsApproved:string;
    accountsApprovedDt:string= new Date().toJSON();
    accountsEmpId:string;
    accountsEmpName:string;
    accountsRemarks:string;
    isSettled:string;
    settleEmpName:string;
    settleRemarks:string;
    settledDt:string= new Date().toJSON();
    cancelledDt:string= new Date().toJSON();
    cancelEmpId:string;
    cancelEmpName:string;
    cancelRemarks:string;
    isEnabled: string;
	createdBy: string;
	modifiedBy: string;
	createdDt: string;
    modifiedDt:  string;
    expenseClaimBills:Array<ExpenseClaimBill>;
}
export class ExpenseClaimBill{
    id:string;
    expenseClaimId:string;
    billDt:string = new Date().toJSON();
    categoryId:string;
    categoryName:string;
    subCategoryId:string;
    subCategoryName:string;
    merchantId:string;
    merchantName:string;
    isBillable:string;
    billAmount:string;
    billRemarks:string;
    docId:string;
    isEnabled: string;
	createdBy: string;
	modifiedBy: string;
	createdDt: string;
    modifiedDt:  string;

}